CREATE TABLE USER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) UNIQUE,
  name VARCHAR(120) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'TEACHER'
);

CREATE TABLE ROOT (
  user_id INT PRIMARY KEY,
  FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE DIRECTOR (
  user_id INT PRIMARY KEY,
  FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE TEACHER (
  user_id INT PRIMARY KEY,
  FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

CREATE TABLE STUDENT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  surname VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  student_group VARCHAR(50) NOT NULL
);

CREATE TABLE ACADEMIC_YEAR (
  id INT AUTO_INCREMENT PRIMARY KEY,
  start_year SMALLINT NOT NULL,
  end_year SMALLINT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  CHECK (end_year = start_year + 1)
);

CREATE TABLE ATTITUDE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  status VARCHAR(30) NOT NULL,
  description VARCHAR(300) NOT NULL,
  created_at DATE NOT NULL DEFAULT (CURRENT_DATE)
);

CREATE TABLE WARNING (
  attitude_id INT PRIMARY KEY,
  FOREIGN KEY (attitude_id) REFERENCES ATTITUDE(id) ON DELETE CASCADE
);

CREATE TABLE RECOGNITION (
  attitude_id INT PRIMARY KEY,
  FOREIGN KEY (attitude_id) REFERENCES ATTITUDE(id) ON DELETE CASCADE
);

CREATE TABLE SCHEDULE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  day_of_week TINYINT NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  CHECK (end_time > start_time),
  CHECK (day_of_week BETWEEN 1 AND 7)
);

CREATE TABLE CONVIVENCE_ROOM (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_date DATE NOT NULL
);

CREATE TABLE RECORD (
  id INT AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(300) NOT NULL,
  record_date DATE NOT NULL
);

CREATE TABLE TASK (
  id INT AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(300) NOT NULL,
  status VARCHAR(30) NOT NULL
);

CREATE TABLE ENROLLMENT (
  student_id INT NOT NULL,
  year_id INT NOT NULL,
  PRIMARY KEY (student_id, year_id),
  FOREIGN KEY (student_id) REFERENCES STUDENT(id) ON DELETE CASCADE,
  FOREIGN KEY (year_id) REFERENCES ACADEMIC_YEAR(id) ON DELETE CASCADE
);

CREATE TABLE LOG_ATTITUDE (
  user_id INT NOT NULL,
  attitude_id INT NOT NULL,
  PRIMARY KEY (user_id, attitude_id),
  FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE,
  FOREIGN KEY (attitude_id) REFERENCES ATTITUDE(id) ON DELETE CASCADE
);

CREATE TABLE ASSIGN_TASK (
  teacher_id INT NOT NULL,
  task_id INT NOT NULL,
  student_id INT NOT NULL,
  PRIMARY KEY (teacher_id, task_id, student_id),
  FOREIGN KEY (teacher_id) REFERENCES TEACHER(user_id) ON DELETE CASCADE,
  FOREIGN KEY (task_id) REFERENCES TASK(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES STUDENT(id) ON DELETE CASCADE
);

CREATE TABLE YEAR_SCHEDULE (
  year_id INT NOT NULL,
  schedule_id INT NOT NULL,
  PRIMARY KEY (year_id, schedule_id),
  FOREIGN KEY (year_id) REFERENCES ACADEMIC_YEAR(id) ON DELETE CASCADE,
  FOREIGN KEY (schedule_id) REFERENCES SCHEDULE(id) ON DELETE CASCADE
);

CREATE TABLE USER_SCHEDULE (
  user_id INT NOT NULL,
  schedule_id INT NOT NULL,
  PRIMARY KEY (user_id, schedule_id),
  FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE,
  FOREIGN KEY (schedule_id) REFERENCES SCHEDULE(id) ON DELETE CASCADE
);

CREATE TABLE ROOM_SCHEDULE (
  schedule_id INT NOT NULL,
  room_id INT NOT NULL,
  PRIMARY KEY (schedule_id, room_id),
  FOREIGN KEY (schedule_id) REFERENCES SCHEDULE(id) ON DELETE CASCADE,
  FOREIGN KEY (room_id) REFERENCES CONVIVENCE_ROOM(id) ON DELETE CASCADE
);

CREATE TABLE ATTENDANCE (
  student_id INT NOT NULL,
  room_id INT NOT NULL,
  PRIMARY KEY (student_id, room_id),
  FOREIGN KEY (student_id) REFERENCES STUDENT(id) ON DELETE CASCADE,
  FOREIGN KEY (room_id) REFERENCES CONVIVENCE_ROOM(id) ON DELETE CASCADE
);

CREATE TABLE OPEN_RECORD (
  user_id INT NOT NULL,
  record_id INT NOT NULL,
  PRIMARY KEY (user_id, record_id),
  FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE,
  FOREIGN KEY (record_id) REFERENCES RECORD(id) ON DELETE CASCADE
);

CREATE TABLE DIRECT (
  director_id INT NOT NULL,
  year_id INT NOT NULL,
  PRIMARY KEY (director_id, year_id),
  FOREIGN KEY (director_id) REFERENCES DIRECTOR(user_id) ON DELETE CASCADE,
  FOREIGN KEY (year_id) REFERENCES ACADEMIC_YEAR(id) ON DELETE CASCADE
);

CREATE TABLE STUDENT_WARNING (
  student_id INT NOT NULL,
  warning_id INT NOT NULL,
  PRIMARY KEY (student_id, warning_id),
  FOREIGN KEY (student_id) REFERENCES STUDENT(id) ON DELETE CASCADE,
  FOREIGN KEY (warning_id) REFERENCES WARNING(attitude_id) ON DELETE CASCADE
);

CREATE TABLE STUDENT_RECOGNITION (
  student_id INT NOT NULL,
  recognition_id INT NOT NULL,
  PRIMARY KEY (student_id, recognition_id),
  FOREIGN KEY (student_id) REFERENCES STUDENT(id) ON DELETE CASCADE,
  FOREIGN KEY (recognition_id) REFERENCES RECOGNITION(attitude_id) ON DELETE CASCADE
);

CREATE TABLE CLASSROOM_ASSIGNMENT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  teacher_id INT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  FOREIGN KEY (student_id) REFERENCES STUDENT(id) ON DELETE CASCADE,
  FOREIGN KEY (teacher_id) REFERENCES TEACHER(user_id) ON DELETE CASCADE
);

CREATE TABLE CLASSROOM_TASK (
  id INT AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  description VARCHAR(300) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  FOREIGN KEY (assignment_id) REFERENCES CLASSROOM_ASSIGNMENT(id) ON DELETE CASCADE
);

CREATE TABLE CLASSROOM_ATTENDANCE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  attendance_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'AUSENTE',
  FOREIGN KEY (assignment_id) REFERENCES CLASSROOM_ASSIGNMENT(id) ON DELETE CASCADE
);

CREATE TABLE DISCIPLINARY_RECORD (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  start_date DATE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Abierto',
  observations VARCHAR(500) DEFAULT '',
  FOREIGN KEY (student_id) REFERENCES STUDENT(id) ON DELETE CASCADE
);

CREATE TABLE RECORD_ATTITUDE (
  record_id INT NOT NULL,
  attitude_id INT NOT NULL,
  PRIMARY KEY (record_id, attitude_id),
  FOREIGN KEY (record_id) REFERENCES DISCIPLINARY_RECORD(id) ON DELETE CASCADE,
  FOREIGN KEY (attitude_id) REFERENCES ATTITUDE(id) ON DELETE CASCADE
);