CREATE TABLE USUARIO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  contraseña VARCHAR(255) NOT NULL
);

CREATE TABLE ROOT (
  id_usuario INT PRIMARY KEY,
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id) ON DELETE CASCADE
);

CREATE TABLE DIRECTIVO (
  id_usuario INT PRIMARY KEY,
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id) ON DELETE CASCADE
);

CREATE TABLE PROFESOR (
  id_usuario INT PRIMARY KEY,
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id) ON DELETE CASCADE
);

CREATE TABLE ALUMNO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  apellido VARCHAR(120) NOT NULL,
  grupo VARCHAR(50) NOT NULL
);

CREATE TABLE CURSO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  anyoinicio SMALLINT NOT NULL,
  anyofin SMALLINT NOT NULL,
  CHECK (anyofin = anyoinicio + 1)
);

CREATE TABLE ACTITUD (
  id INT AUTO_INCREMENT PRIMARY KEY,
  estado VARCHAR(30) NOT NULL,
  descripcion VARCHAR(300) NOT NULL
);

CREATE TABLE AMONESTACION (
  id_actitud INT PRIMARY KEY,
  FOREIGN KEY (id_actitud) REFERENCES ACTITUD(id) ON DELETE CASCADE
);

CREATE TABLE RECONOCIMIENTO (
  id_actitud INT PRIMARY KEY,
  FOREIGN KEY (id_actitud) REFERENCES ACTITUD(id) ON DELETE CASCADE
);

CREATE TABLE HORARIO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dia TINYINT NOT NULL,
  horainicio TIME NOT NULL,
  horafin TIME NOT NULL,
  CHECK (horafin > horainicio),
  CHECK (dia BETWEEN 1 AND 7)
);

CREATE TABLE AULA_CONVIVENCIA (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fecha DATE NOT NULL
);

CREATE TABLE EXPEDIENTE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  descripcion VARCHAR(300) NOT NULL,
  fecha DATE NOT NULL
);

CREATE TABLE TAREA (
  id INT AUTO_INCREMENT PRIMARY KEY,
  descripcion VARCHAR(300) NOT NULL,
  estado VARCHAR(30) NOT NULL
);

CREATE TABLE MATRICULA (
  id_alumno INT NOT NULL,
  id_curso INT NOT NULL,
  PRIMARY KEY (id_alumno, id_curso),
  FOREIGN KEY (id_alumno) REFERENCES ALUMNO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_curso) REFERENCES CURSO(id) ON DELETE CASCADE
);

CREATE TABLE REGISTRA (
  id_usuario INT NOT NULL,
  id_actitud INT NOT NULL,
  PRIMARY KEY (id_usuario, id_actitud),
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_actitud) REFERENCES ACTITUD(id) ON DELETE CASCADE
);

CREATE TABLE ASIGNA_TAREA (
  id_profesor INT NOT NULL,
  id_tarea INT NOT NULL,
  id_alumno INT NOT NULL,
  PRIMARY KEY (id_profesor, id_tarea, id_alumno),
  FOREIGN KEY (id_profesor) REFERENCES PROFESOR(id_usuario) ON DELETE CASCADE,
  FOREIGN KEY (id_tarea) REFERENCES TAREA(id) ON DELETE CASCADE,
  FOREIGN KEY (id_alumno) REFERENCES ALUMNO(id) ON DELETE CASCADE
);

CREATE TABLE CURSO_HORARIO (
  id_curso INT NOT NULL,
  id_horario INT NOT NULL,
  PRIMARY KEY (id_curso, id_horario),
  FOREIGN KEY (id_curso) REFERENCES CURSO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_horario) REFERENCES HORARIO(id) ON DELETE CASCADE
);

CREATE TABLE TIENE_HORARIO (
  id_usuario INT NOT NULL,
  id_horario INT NOT NULL,
  PRIMARY KEY (id_usuario, id_horario),
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_horario) REFERENCES HORARIO(id) ON DELETE CASCADE
);

CREATE TABLE HORARIO_AULA (
  id_horario INT NOT NULL,
  id_aula INT NOT NULL,
  PRIMARY KEY (id_horario, id_aula),
  FOREIGN KEY (id_horario) REFERENCES HORARIO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_aula) REFERENCES AULA_CONVIVENCIA(id) ON DELETE CASCADE
);

CREATE TABLE ASISTE (
  id_alumno INT NOT NULL,
  id_aula INT NOT NULL,
  PRIMARY KEY (id_alumno, id_aula),
  FOREIGN KEY (id_alumno) REFERENCES ALUMNO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_aula) REFERENCES AULA_CONVIVENCIA(id) ON DELETE CASCADE
);

CREATE TABLE ABRE (
  id_usuario INT NOT NULL,
  id_expediente INT NOT NULL,
  PRIMARY KEY (id_usuario, id_expediente),
  FOREIGN KEY (id_usuario) REFERENCES USUARIO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_expediente) REFERENCES EXPEDIENTE(id) ON DELETE CASCADE
);

CREATE TABLE DIRIGE (
  id_directivo INT NOT NULL,
  id_curso INT NOT NULL,
  PRIMARY KEY (id_directivo, id_curso),
  FOREIGN KEY (id_directivo) REFERENCES DIRECTIVO(id_usuario) ON DELETE CASCADE,
  FOREIGN KEY (id_curso) REFERENCES CURSO(id) ON DELETE CASCADE
);

CREATE TABLE OBTIENE_AMONESTACION (
  id_alumno INT NOT NULL,
  id_amonestacion INT NOT NULL,
  PRIMARY KEY (id_alumno, id_amonestacion),
  FOREIGN KEY (id_alumno) REFERENCES ALUMNO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_amonestacion) REFERENCES AMONESTACION(id_actitud) ON DELETE CASCADE
);

CREATE TABLE OBTIENE_RECONOCIMIENTO (
  id_alumno INT NOT NULL,
  id_reconocimiento INT NOT NULL,
  PRIMARY KEY (id_alumno, id_reconocimiento),
  FOREIGN KEY (id_alumno) REFERENCES ALUMNO(id) ON DELETE CASCADE,
  FOREIGN KEY (id_reconocimiento) REFERENCES RECONOCIMIENTO(id_actitud) ON DELETE CASCADE
);